services:
  web:
    build: .
    environment:
      DB_HOST: mariadb
      DB_USER: root
      DB_PASS: ''
      DB_NAME: 'blog'
    ports:
      - "80:80"

  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./bdd/blog.sql:/docker-entrypoint-initdb.d/blog.sql

  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "8080:80"

volumes:
  mariadb_data: